In [1]:
import torch
import torchani
from pathlib import Path

In [1]:
state_dict = torch.load('/home/nick/Pt/best.pt')

NameError: name 'torch' is not defined

In [3]:
state_dict

OrderedDict([('0.0.weight',
              tensor([[ 0.1097,  0.1542,  0.1122,  ..., -0.0183,  0.0003,  0.0399],
                      [ 0.0266,  0.0511,  0.0981,  ...,  0.0863,  0.0153,  0.0063],
                      [-0.0317, -0.1705, -0.0655,  ..., -0.1028, -0.0112,  0.0131],
                      ...,
                      [-0.0157, -0.1614, -0.0342,  ...,  0.0204, -0.0966, -0.0150],
                      [-0.0626, -0.0484, -0.0339,  ..., -0.1442, -0.0348, -0.0269],
                      [-0.0216,  0.1436, -0.0102,  ..., -0.0244,  0.0077,  0.0145]],
                     device='cuda:0')),
             ('0.0.bias',
              tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                    

In [13]:
aev_computer = torchani.AEVComputer.like_1x(use_cuda_extension=True)

aev_dim = aev_computer.aev_length
print(aev_dim)
H_network = torch.nn.Sequential(
    torch.nn.Linear(aev_dim, 160),
    torch.nn.CELU(0.1),
    torch.nn.Linear(160, 128),
    torch.nn.CELU(0.1),
    torch.nn.Linear(128, 96),
    torch.nn.CELU(0.1),
    torch.nn.Linear(96, 1)
)

C_network = torch.nn.Sequential(
    torch.nn.Linear(aev_dim, 144),
    torch.nn.CELU(0.1),
    torch.nn.Linear(144, 112),
    torch.nn.CELU(0.1),
    torch.nn.Linear(112, 96),
    torch.nn.CELU(0.1),
    torch.nn.Linear(96, 1)
)

N_network = torch.nn.Sequential(
    torch.nn.Linear(aev_dim, 128),
    torch.nn.CELU(0.1),
    torch.nn.Linear(128, 112),
    torch.nn.CELU(0.1),
    torch.nn.Linear(112, 96),
    torch.nn.CELU(0.1),
    torch.nn.Linear(96, 1)
)

O_network = torch.nn.Sequential(
    torch.nn.Linear(aev_dim, 128),
    torch.nn.CELU(0.1),
    torch.nn.Linear(128, 112),
    torch.nn.CELU(0.1),
    torch.nn.Linear(112, 96),
    torch.nn.CELU(0.1),
    torch.nn.Linear(96, 1)
)
modules = [H_network,C_network,N_network,O_network]

384


In [5]:
nn = torchani.ANIModel(modules)

In [6]:
nn

ANIModel(
  (0): Sequential(
    (0): Linear(in_features=384, out_features=160, bias=True)
    (1): CELU(alpha=0.1)
    (2): Linear(in_features=160, out_features=128, bias=True)
    (3): CELU(alpha=0.1)
    (4): Linear(in_features=128, out_features=96, bias=True)
    (5): CELU(alpha=0.1)
    (6): Linear(in_features=96, out_features=1, bias=True)
  )
  (1): Sequential(
    (0): Linear(in_features=384, out_features=144, bias=True)
    (1): CELU(alpha=0.1)
    (2): Linear(in_features=144, out_features=112, bias=True)
    (3): CELU(alpha=0.1)
    (4): Linear(in_features=112, out_features=96, bias=True)
    (5): CELU(alpha=0.1)
    (6): Linear(in_features=96, out_features=1, bias=True)
  )
  (2): Sequential(
    (0): Linear(in_features=384, out_features=128, bias=True)
    (1): CELU(alpha=0.1)
    (2): Linear(in_features=128, out_features=112, bias=True)
    (3): CELU(alpha=0.1)
    (4): Linear(in_features=112, out_features=96, bias=True)
    (5): CELU(alpha=0.1)
    (6): Linear(in_features

In [9]:
device = torch.device('cpu')
nn.load_state_dict(state_dict,  strict=False)
model = torch.nn.Sequential(nn).to(device)
print(model)

Sequential(
  (0): ANIModel(
    (0): Sequential(
      (0): Linear(in_features=384, out_features=160, bias=True)
      (1): CELU(alpha=0.1)
      (2): Linear(in_features=160, out_features=128, bias=True)
      (3): CELU(alpha=0.1)
      (4): Linear(in_features=128, out_features=96, bias=True)
      (5): CELU(alpha=0.1)
      (6): Linear(in_features=96, out_features=1, bias=True)
    )
    (1): Sequential(
      (0): Linear(in_features=384, out_features=144, bias=True)
      (1): CELU(alpha=0.1)
      (2): Linear(in_features=144, out_features=112, bias=True)
      (3): CELU(alpha=0.1)
      (4): Linear(in_features=112, out_features=96, bias=True)
      (5): CELU(alpha=0.1)
      (6): Linear(in_features=96, out_features=1, bias=True)
    )
    (2): Sequential(
      (0): Linear(in_features=384, out_features=128, bias=True)
      (1): CELU(alpha=0.1)
      (2): Linear(in_features=128, out_features=112, bias=True)
      (3): CELU(alpha=0.1)
      (4): Linear(in_features=112, out_features=

In [14]:
from torchani.datasets import ANIDataset
ds_path = Path('/home/nick/First_DSs/ANI-1x-first-conformers.h5')
ds = ANIDataset(locations=ds_path, names='1x first')
ch4 = (ds['CH4']['species'],ds['CH4']['coordinates'])
print(ch4)
ani2x = torchani.models.ANI2x()
#print(ani2x)
#print(ani2x(ch4))
nn(ch4)

(tensor([[6, 1, 1, 1, 1]]), tensor([[[ 4.9725e-04, -2.3656e-02, -4.6554e-02],
         [-9.4934e-01, -4.6713e-01, -2.1225e-01],
         [-2.1828e-01,  6.4611e-01,  8.7319e-01],
         [ 3.7291e-01,  6.5190e-01, -6.9571e-01],
         [ 7.9173e-01, -6.8895e-01,  3.1410e-01]]]))


RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 384x144)